package kb

import (
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/kittors/AgentFlow/internal/projectroot"
)

type TemplateInitSummary struct {
	ProjectType  string   `json:"project_type"`
	FilesCreated []string `json:"files_created"`
}

var indicators = map[string][]string{
	"frontend": {
		"package.json",
		"vite.config.ts",
		"next.config.js",
		"next.config.ts",
		"nuxt.config.ts",
		"angular.json",
		"svelte.config.js",
	},
	"backend": {
		"requirements.txt",
		"Pipfile",
		"go.mod",
		"Cargo.toml",
		"pom.xml",
		"build.gradle",
	},
	"python": {
		"pyproject.toml",
		"setup.py",
		"setup.cfg",
	},
}

func DetectProjectType(root string) string {
	hasFrontend := containsAny(root, indicators["frontend"])
	hasBackend := containsAny(root, indicators["backend"])
	hasPython := containsAny(root, indicators["python"])

	switch {
	case hasFrontend && hasBackend:
		return "fullstack"
	case hasFrontend:
		return "frontend"
	case hasPython:
		return "python"
	case hasBackend:
		return "backend"
	default:
		return "python"
	}
}

func InitPaths(root string) (TemplateInitSummary, error) {
	paths := projectroot.NewPaths(root)
	dirs := []string{
		paths.Modules,
		paths.Plan,
		paths.Graph,
		paths.Conventions,
		paths.Archive,
		paths.Sessions,
	}
	for _, dir := range dirs {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return TemplateInitSummary{}, err
		}
	}

	projectType := DetectProjectType(root)
	filesCreated, err := ensureCoreFiles(paths, projectType)
	if err != nil {
		return TemplateInitSummary{}, err
	}

	return TemplateInitSummary{
		ProjectType:  projectType,
		FilesCreated: filesCreated,
	}, nil
}

func containsAny(root string, names []string) bool {
	for _, name := range names {
		if _, err := os.Stat(filepath.Join(root, name)); err == nil {
			return true
		}
	}
	return false
}

func ensureCoreFiles(paths projectroot.Paths, projectType string) ([]string, error) {
	files := []struct {
		path    string
		content string
	}{
		{path: filepath.Join(paths.KB, "INDEX.md"), content: defaultIndexContent(paths.ProjectRoot, projectType)},
		{path: filepath.Join(paths.KB, "context.md"), content: defaultContextContent(paths.ProjectRoot, projectType)},
		{path: filepath.Join(paths.KB, "CHANGELOG.md"), content: defaultChangelogContent()},
	}

	created := make([]string, 0, len(files))
	for _, file := range files {
		if _, err := os.Stat(file.path); err == nil {
			continue
		}
		if err := os.WriteFile(file.path, []byte(file.content), 0o644); err != nil {
			return nil, err
		}
		rel, err := filepath.Rel(paths.ProjectRoot, file.path)
		if err != nil {
			return nil, err
		}
		created = append(created, filepath.ToSlash(rel))
	}
	return created, nil
}

func defaultIndexContent(root, projectType string) string {
	projectName := projectroot.ProjectName(root)
	return strings.Join([]string{
		"# Project Overview",
		"",
		"- Project: `" + projectName + "`",
		"- Type: `" + projectType + "`",
		"- Root: `" + filepath.ToSlash(root) + "`",
		"",
		"## Notes",
		"- Generated by `agentflow init`.",
		"- Module inventory is maintained in `modules/_index.md`.",
		"",
	}, "\n")
}

func defaultContextContent(root, projectType string) string {
	stackHints := detectStackHints(root)
	lines := []string{
		"# Technical Context",
		"",
		"- Project: `" + projectroot.ProjectName(root) + "`",
		"- Project Type: `" + projectType + "`",
		"",
		"## Detected Signals",
	}
	if len(stackHints) == 0 {
		lines = append(lines, "- No obvious stack markers detected yet.")
	} else {
		for _, hint := range stackHints {
			lines = append(lines, "- "+hint)
		}
	}
	lines = append(lines, "", "## Maintenance", "- Updated via Go-native AgentFlow commands.", "")
	return strings.Join(lines, "\n")
}

func defaultChangelogContent() string {
	return strings.Join([]string{
		"# KB Changelog",
		"",
		"- Initialized by `agentflow init` on " + time.Now().UTC().Format(time.RFC3339) + ".",
		"",
	}, "\n")
}

func detectStackHints(root string) []string {
	candidates := []struct {
		file string
		hint string
	}{
		{file: "go.mod", hint: "Go module detected via `go.mod`."},
		{file: "package.json", hint: "Node.js package detected via `package.json`."},
		{file: "Cargo.toml", hint: "Rust crate detected via `Cargo.toml`."},
		{file: "pom.xml", hint: "Java Maven project detected via `pom.xml`."},
		{file: "build.gradle", hint: "Gradle build detected via `build.gradle`."},
		{file: "pyproject.toml", hint: "Python project markers detected via `pyproject.toml`."},
	}

	hints := make([]string, 0, len(candidates))
	for _, candidate := range candidates {
		if _, err := os.Stat(filepath.Join(root, candidate.file)); err == nil {
			hints = append(hints, candidate.hint)
		}
	}
	return hints
}
